name: "ModuleMap"
backend: "python"

version_policy: {
  specific: { versions: [1] }
}

instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [0]
  }
]

input [
  {
    name: "FEATURES"
    data_type: TYPE_FP32
    dims: [ -1, 16 ]
  }
]

output [
  {
    name: "LABELS"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]

parameters: {
  key: "auto_cast",
  value: {string_value: "False"}
}

parameters: {
  key: "compiling",
  value: {string_value: "False"}
}

parameters: {
  key: "debug",
  value: {string_value: "False"}
}

parameters: {
  key: "save_event",
  value: {string_value: "False"}
}

parameters: {
  key: "timing_output_dir",
  value: { string_value: "/pscratch/sd/a/alazar/autowork/logs/tracking/timing" }
}

parameters: {
  key: "timing_output_file",
  value: { string_value: "DoubleMetricLearning_1_timing.csv" }
}

parameters: {
  key: "module_map_pattern_path",
  value: {string_value: "ModuleMap_rel24_ttbar_v9_89809evts_tol1e-10"}
}