name: "GNN4Pixel"
backend: "python"

input [
  {
    name: "FEATURES"
    data_type: TYPE_FP32
    dims: [ -1, 15 ]
  }
]

output [
  {
    name: "LABELS"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]


instance_group [
  {
    count: 1
    kind: KIND_GPU
   }
]

parameters: {
  key: "r_max",
  value: {string_value: "0.11"}
}

parameters: {
  key: "k_max",
  value: {string_value: "300"}
}

parameters: {
  key: "filter_cut",
  value: {string_value: "0.2"}
}

parameters: {
  key: "filter_batches",
  value: {string_value: "10"}
}

parameters: {
  key: "cc_cut",
  value: {string_value: "0.01"}
}

parameters: {
  key: "walk_min",
  value: {string_value: "0.1"}
}

parameters: {
  key: "walk_max",
  value: {string_value: "0.6"}
}

parameters: {
  key: "debug",
  value: {string_value: "true"}
}

parameters: {
  key: "r_index",
  value: {string_value: "0"}
}

parameters: {
  key: "z_index",
  value: {string_value: "2"}
}
