name: "DoubleMetricLearning"
backend: "python"

version_policy: {
  specific: { versions: [1] }
}

input [
  {
    name: "FEATURES"
    data_type: TYPE_FP32
    dims: [ -1, 44 ]
  }
]

output [
  {
    name: "LABELS"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]


instance_group [
  {
    count: 1
    kind: KIND_GPU
   }
]

parameters: {
  key: "auto_cast",
  value: {string_value: "True"}
}

parameters: {
  key: "compiling",
  value: {string_value: "True"}
}

parameters: {
  key: "debug",
  value: {string_value: "False"}
}

parameters: {
  key: "save_event",
  value: {string_value: "False"}
}

parameters: {
  key: "timing_output_dir",
  value: { string_value: "/pscratch/sd/a/alazar/autowork/logs/tracking/timing" }
}

parameters: {
  key: "timing_output_file",
  value: { string_value: "DoubleMetricLearning_1_timing.csv" }
}