name: "ExatrkX4PixelPython"
backend: "python"

input [
  {
    name: "FEATURES"
    data_type: TYPE_FP32
    dims: [ -1, 15 ]
  }
]

output [
  {
    name: "LABELS"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]


instance_group [
  {
    count: 1
    kind: KIND_GPU
   }
]

parameters: {
  key: "embedding_fname",
  value: {string_value: "embedding.pt"}
}

parameters: {
  key: "gnn_fname",
  value: {string_value: "edge_classifier-ChainedInteractionGNN2-v4.pt"}
}

parameters: {
  key: "r_max",
  value: {string_value: "0.10"}
}

parameters: {
  key: "k_max",
  value: {string_value: "250"}
}

parameters: {
  key: "debug",
  value: {string_value: "true"}
}
