name: "ExatrkX4PixelPythonWithFilter"
backend: "python"

input [
  {
    name: "FEATURES"
    data_type: TYPE_FP32
    dims: [ -1, 15 ]
  }
]

output [
  {
    name: "LABELS"
    data_type: TYPE_INT64
    dims: [ -1 ]
  }
]


instance_group [
  {
    count: 1
    kind: KIND_GPU
   }
]

parameters: {
  key: "embedding_fname",
  value: {string_value: "embedding.pt"}
}

parameters: {
  key: "r_max",
  value: {string_value: "0.11"}
}

parameters: {
  key: "k_max",
  value: {string_value: "300"}
}

parameters: {
  key: "filter_fname",
  value: {string_value: "filter.pt"}
}

parameters: {
  key: "filter_cut",
  value: {string_value: "0.2"}
}

parameters: {
  key: "gnn_fname",
  value: {string_value: "gnn.pt"}
}

parameters: {
  key: "score_cut_cc",
  value: {string_value: "0.11"}
}

parameters: {
  key: "score_cut_walk_min",
  value: {string_value: "300"}
}

parameters: {
  key: "score_cut_walk_max",
  value: {string_value: "300"}
}

parameters: {
  key: "debug",
  value: {string_value: "true"}
}
